name: Deploy Next JS to GAE

# Controls when the workflow will run
on:
  push:
    branches: [main, development]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploying Next JS to Google Cloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "20.2.0"

      - name: Install Dependencies with npm
        run: npm install

      - name: Building frontend
        run: npm run build

      - name: Deploy to App Engine
        if: github.ref == 'refs/heads/main'
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: app.yaml
          version: v1
          project_id: ${{ secrets.PROJECT_ID }}
          credentials: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Deploy Dispatch Configuration
        if: github.ref == 'refs/heads/main'
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: dispatch.yaml
          project_id: ${{ secrets.PROJECT_ID }}
          credentials: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Deploy to App Engine
        if: github.ref == 'refs/heads/development'
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: test-app.yaml
          version: v1
          project_id: ${{ secrets.TEST_PROJECT_ID }}
          credentials: ${{ secrets.TEST_SERVICE_ACCOUNT }}

      - name: Deploy Dispatch Configuration
        if: github.ref == 'refs/heads/development'
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: test-dispatch.yaml
          project_id: ${{ secrets.TEST_PROJECT_ID }}
          credentials: ${{ secrets.TEST_SERVICE_ACCOUNT }}
