name: Deploy Next JS to GAE

# Controls when the workflow will run
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploying Next JS to Google Cloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "18.17.0"

      # Caching Dependencies and Build Output
      - name: Cache Yarn Dependencies and Next.js Build Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.yarn
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-

      - name: Install Dependencies with Yarn
        run: yarn install --frozen-lockfile

      - name: Building frontend
        run: |
          yarn build # Building the app with Yarn

      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: app.yaml
          version: v1
          project_id: ${{ secrets.PROJECT_ID }}
          credentials: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Deploy Dispatch Configuration
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: dispatch.yaml
          project_id: ${{ secrets.PROJECT_ID }}
          credentials: ${{ secrets.SERVICE_ACCOUNT }}