name: Deploy Next JS to GAE

# Controls when the workflow will run
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploying Next JS to Google Cloud
    runs-on: ubuntu-latest
    env:
      NODE_ENV: "production"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "20.3.0"

      - name: Install Dependencies with npm
        run: npm install

      - name: Building frontend
        run: |
          npm run build # Building the app with npm

      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: app.yaml
          version: v1
          project_id: ${{ secrets.PROJECT_ID }}
          credentials: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Deploy Dispatch Configuration
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: dispatch.yaml
          project_id: ${{ secrets.PROJECT_ID }}
          credentials: ${{ secrets.SERVICE_ACCOUNT }}
